//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez odpowiednie narzędzie.
//
//     Zmiany w tym pliku mogą być przyczyną niepoprawnego zachowania i zostaną utracone w przypadku
//     ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Market365_3._0.Zamówienia
{
    public partial class Zamówienia
    {

        /// <summary>
        /// Kontrolka form1.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
